[build]
  base    = "client"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  # VITE_API_URL, etc.

# <<< Esto es lo que debe ir al final >>>
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200