CREATE TABLE IF NOT EXISTS paquetes (
  id SERIAL PRIMARY KEY,
  depto VARCHAR NOT NULL,
  fecha_ingreso TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
  estado VARCHAR NOT NULL DEFAULT 'pendiente'
);
